const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod")
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_GENAI_API_KEY });


async function generateInterviewReport({ resume, jobDescription }) {
    const prompt = `
You are an expert interview coach. Analyze the resume and job description.
Return ONLY a valid JSON object with this EXACT structure, no extra text:

{
  "matchScore": 85,
  "title": "Job title here",
  "technicalQuestions": [
    { "question": "...", "intention": "...", "answer": "..." }
  ],
  "behavioralQuestions": [
    { "question": "...", "intention": "...", "answer": "..." }
  ],
  "skillsGap": [
    { "skill": "...", "severity": "Low | Medium | High" }
  ],
  "preparationTips": [
    { "day": 1, "focusArea": "...", "task": ["task1", "task2"] }
  ]
}

Resume:
${resume}

Job Description:
${jobDescription}
    `;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: { responseMimeType: "application/json" },
        });

        const text = response?.text || response?.output?.[0]?.content?.[0]?.text;
        if (!text) {
            throw new Error(`Empty AI response: ${JSON.stringify(response)}`);
        }

        try {
            return JSON.parse(text);
        } catch (parseError) {
            // Try to extract JSON from wrapped text (if model added markdown fences)
            const trimmed = text.trim();
            const jsonMatch = trimmed.match(/\{[\s\S]*\}/);
            if (jsonMatch) {
                return JSON.parse(jsonMatch[0]);
            }
            throw new Error(`Cannot parse AI response as JSON: ${parseError.message}; text=${text}`);
        }
    } catch (error) {
        console.error('generateInterviewReport error:', {
            message: error.message,
            stack: error.stack,
            response: error.response ? {
                status: error.response.status,
                data: error.response.data
            } : null
        });
        throw error;
    }
}

async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch({
        headless: 'new',
        args: [
            '--no-sandbox',                      // ✅ required on Render/Linux
            '--disable-setuid-sandbox',          // ✅ required on Render/Linux
            '--disable-dev-shm-usage',           // ✅ prevents memory issues
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--single-process',                  // ✅ important for Render free tier
            '--disable-gpu'
        ],
        executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined
    })
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to pdf using puppeteer")
    })

    //     const prompt = `Generate a ATS- friendly resume  for a candidate with the following details:
    //                     Resume: ${resume}
    //                     job Description: ${jobDescription}
    //                      the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
    //                         The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
    //                         The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
    //                         you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
    //                         The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
    //                         The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
    // `
    const prompt = `
You are an expert resume writer and ATS optimization specialist with 10+ years of experience helping candidates land interviews at top companies.

Analyze the candidate's resume and job description carefully, then generate a tailored, ATS-friendly, single-page HTML resume.

CANDIDATE DATA:
Resume: ${resume}
Job Description: ${jobDescription}

STRICT RULES — follow every one:

1. SINGLE PAGE ONLY — the entire resume MUST fit in exactly one A4 page (794px × 1123px). Never exceed this. Cut ruthlessly if needed.
2. ATS FRIENDLY — use plain semantic HTML only: <h1>, <h2>, <p>, <ul>, <li>, <a>. Zero tables, zero CSS Grid, zero Flexbox tricks that confuse parsers. All text must be selectable (no image-based text).
3. WORKING LINKS — make email, LinkedIn, GitHub, and portfolio links fully clickable:
   - Email: <a href="mailto:email@example.com">email@example.com</a>
   - LinkedIn: <a href="https://linkedin.com/in/username">linkedin.com/in/username</a>
   - GitHub: <a href="https://github.com/username">github.com/username</a>
   Only include links that exist in the candidate's data. Never fabricate links.
4. TAILORED CONTENT — rewrite bullet points to mirror keywords from the job description naturally. Do NOT stuff keywords unnaturally. Sound like a real human, not AI.
5. QUANTIFY EVERYTHING — convert vague claims into measurable achievements:
   - Bad: "Improved app performance"
   - Good: "Reduced API response time by 40% through query optimization and Redis caching"
6. STRONG ACTION VERBS — start every bullet with: Engineered, Architected, Optimized, Delivered, Reduced, Increased, Built, Led, Implemented, Designed, Automated, Integrated, Streamlined, Launched, Mentored
7. NO AI LANGUAGE — never use: "leveraged", "spearheaded", "utilized", "passionate", "results-driven", "dynamic", "synergy", "innovative". Write like a confident engineer, not a cover letter bot.
8. CONTENT PRIORITY ORDER:
   - Header (name + contact + links)
   - Professional Summary (2-3 lines max, tailored to JD)
   - Technical Skills (keywords from JD first)
   - Work Experience (reverse chronological, 2-3 bullets per role)
   - Projects (2 max, most relevant to JD)
   - Education

HTML + CSS DESIGN RULES:
- Page size: width 794px, min-height 1123px, padding 36px 44px
- Font: 'Inter' from Google Fonts — import it
- Font sizes: Name=22px, Section headers=11px uppercase, Body=12px, Line height=1.5
- Colors: Name=#1a1a2e (dark navy), Section headers=#6c63ff (accent), Borders=#e8e8f0, Body text=#2d2d2d, Muted=#6b7280
- Section header style: 11px, uppercase, letter-spacing 0.08em, color #6c63ff, border-bottom: 1.5px solid #6c63ff, padding-bottom 3px, margin-bottom 8px
- Links: color #6c63ff, no underline, hover not needed (PDF)
- Bullets: margin-left 14px, bullet color #6c63ff (use CSS list-style or ::before)
- NO box shadows, NO gradients, NO decorative elements that confuse ATS
- Inline all CSS in a single <style> tag inside <head>
- All spacing must be tight — margin/padding values between 2px–12px only
- Use @page { size: A4; margin: 0; } for PDF rendering

CRITICAL PDF RULES for Puppeteer:
- Set body margin: 0, padding: 0
- Wrap everything in a div with: width: 794px; max-height: 1123px; overflow: hidden
- Use pt units for font sizes when possible (10pt body, 8pt small text)
- Avoid page-break issues — keep sections together with page-break-inside: avoid

RESPONSE FORMAT:
Return ONLY a valid JSON object. No markdown, no backticks, no explanation:
{"html": "<complete HTML string here>"}

The HTML must be a complete valid document from <!DOCTYPE html> to </html>.
All CSS must be inside a <style> tag in <head>.
The resume must look like it was crafted by a human professional, not generated.
`
    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema),
        }
    })


    const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer
}

module.exports = { generateInterviewReport, generateResumePdf };